const tintColorLight = "#2f95dc";
const tintColorDark = "#fff";

export default {
  light: {
    text: "#000",
    background: "#fff",
    tint: tintColorLight,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#fff",
    background: "#000",
    tint: tintColorDark,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorDark,
  },
  black: "#000000",
  white: "#FFFFFF",
  whiteSmoke: "#F5F5F5",
  orange: "#EF6506",
  lightPeach: "#FFF4EC",
  amaranth: "#EC254E",
  transparent: "transparent",
  gainsboro: "#DADADA",
  show: "#FEF9F8",
  matterhorn: "#4B4B4B",
  bittersweet: "#FF7A60",
  dodgerBlue: "#1D9BF0",
  nero: "#222222",
  raven: "#687684",
  grey: "#868686",
  aquaSqueeze: "#757575",
  aquaSqueeze2: "#797979",
  whisper: "#EBEBEB",
  peach: "#FFCBA9",
  goldenGlow: "#F9D477",
  nobel: "#979797",
  titanium: "#E02B00",
  carrot: "#F15D22",
  yellowPink: "#FFE9AF",
  primaryLightOrange: "#FFF8F3",
  romantic: "#FCC29C",
  cerulean: "#006699",
};
